version: "3"

services:
  app:
    build: .
    volumes:
      - ./photos:/app/frame-interpolation/photos
      - ./pretrained_models:/app/frame-interpolation/pretrained_models
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    tty: true
    